version: 2
updates:
  # Проверка корневого package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "npm"
      include: "scope"
    ignore:
      # Игнорировать обновления мажорных версий из-за возможной несовместимости
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Проверка package.json в директории frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "frontend"
      include: "scope"
    ignore:
      # Игнорировать обновления мажорных версий из-за возможной несовместимости
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Проверка requirements.txt в директории backend
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "backend"
      include: "scope"
    ignore:
      # Игнорировать обновления мажорных версий из-за возможной несовместимости
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Проверка обновлений для GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "ci-cd"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope" 